/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace_2_20_02_32/packages/ti/mcu/msp430/csl/interrupt_vectors/InterruptVectors_init.xdt
 */
#include <msp430.h>

/* USER CODE START (section: InterruptVectors_init_c_prologue) */
extern volatile int secCount;
extern volatile unsigned char sensor_ready, tamper_count;
extern volatile unsigned char eightCount;			// counts clock interrupts every eighth of a second, wakes up every 8 counts

/* USER CODE END (section: InterruptVectors_init_c_prologue) */

/*
 *  ======== InterruptVectors_graceInit ========
 */
void InterruptVectors_graceInit(void)
{
}

/*
 *  ======== Timer0_B3 Interrupt Service Routine ======== 
 */
#pragma vector=TIMER0_B0_VECTOR
__interrupt void TIMER0_B0_ISR_HOOK(void)
{
    /* USER CODE START (section: TIMER0_B0_ISR_HOOK) */
	// this interrupt happens every 1/8 second
	P2OUT &= ~ BIT7;				// turn the LED off
	if (P2IN & BIT2) P2OUT |= BIT7;	// mimic the TSB_PHNMON input
	if (++eightCount > 7)			// do nothing most of the time
	{ 	eightCount = 0 ;			// reset the counter every second
		if (++tamper_count > 9) tamper_count = 0 ;	// Check for a tamper condition every 10 seconds
		secCount--;									// decrement the time out countdown counter every second
		__low_power_mode_off_on_exit();				// Every second the main loop starts up again
	}
    /* USER CODE END (section: TIMER0_B0_ISR_HOOK) */
}


